actions_dict = {
    1: 'Swipe left',
    2: 'Swipe right',
    3: 'Wave',
    4: 'Clap',
    5: 'Throw',
    6: 'Arm cross',
    7: 'Basketball shoot',
    8: 'Draw X',
    9: 'Draw circle (clockwise)',
    10: 'Draw circle (counter clockwise)',
    11: 'Draw triangle',
    12: 'Bowling',
    13: 'Boxing',
    14: 'Baseball swing',
    15: 'Tennis swing',
    16: 'Arm curl',
    17: 'Tennis serve',
    18: 'Push',
    19: 'Knock',
    20: 'Catch',
    21: 'Pickup and throw',
    22: 'Jog',
    23: 'Walk',
    24: 'Sit to stand',
    25: 'Stand to sit',
    26: 'Lunge',
    27: 'Squat'
}

reverse_actions_dict = {
    'Swipe left': 1,
    'Swipe right': 2,
    'Wave': 3,
    'Clap': 4,
    'Throw': 5,
    'Arm cross': 6,
    'Basketball shoot': 7,
    'Draw X': 8,
    'Draw circle (clockwise)': 9,
    'Draw circle (counter clockwise)': 10,
    'Draw triangle': 11,
    'Bowling': 12,
    'Boxing': 13,
    'Baseball swing': 14,
    'Tennis swing': 15,
    'Arm curl': 16,
    'Tennis serve': 17,
    'Push': 18,
    'Knock': 19,
    'Catch': 20,
    'Pickup and throw': 21,
    'Jog': 22,
    'Walk': 23,
    'Sit to stand': 24,
    'Stand to sit': 25,
    'Lunge': 26,
    'Squat': 27
}